### ISSUE TITLE
Lab Documentation format Problem

### ISSUE THREAD

**Issue by golden-eye1** [uOttawaDrone/drone-fall-2019#8]
### Lab Documentation format Problem
* We encountered some problems with the template where the markdown code would be recognized.
* If you do encounter any issues try playing with the document indentation.

**Comment by FaizChishtie** [comment]
Try removing the % signs! That should help.

You can also see a preview of your document by clicking the `Preview Changes` button on the top right!


<img width="429" alt="Screen Shot 2019-11-19 at 4 03 29 PM" src="https://user-images.githubusercontent.com/31967593/69186255-310e5480-0ae6-11ea-9077-a06cdc6c0387.png">
