### ISSUE TITLE
Lab Documentation link Problems

### ISSUE THREAD

**Issue by SharabhojI** [uOttawaDrone/drone-fall-2019#9]
# Lab Documentation link Problems
* Encountering issues with opening image links in the lab documentation. 
* Links redirect to back to documentation rather than the image. 
* Issue could possibly be related to markdown.

**Comment by FaizChishtie** [comment]
This can be solved by removing the %'s in the template ;).

Sorry I should have made that more clear!

For example: 
```
   ![Power Supply Board](https://github.com/uOttawaDrone/drone-fall-2019/blob/master/docs/Lab%20Picture/power%20supply%20board.jpg "PSB picture")
```

   ![Power Supply Board](https://github.com/uOttawaDrone/drone-fall-2019/blob/master/docs/Lab%20Picture/power%20supply%20board.jpg "PSB picture")

<img width="928" alt="Screen Shot 2019-11-19 at 3 57 42 PM" src="https://user-images.githubusercontent.com/31967593/69185915-9ca3f200-0ae5-11ea-8150-7dd8be46d4e7.png">
